#!/usr/bin/awk -f

# LMDBG helper script
#
# Input:
#   malloc/realloc/free ...
#    address1
#    address2
#    address3
# Output:
#   malloc/realloc/free ...<SUBSEP>address1<SUBSEP>address2<SUBSEP>address3

NF > 0 && /^ / {
	calls = calls SUBSEP $0
	next
}

NF > 0 {
	if (last){
		print last " " calls
		calls = ""
	}

	last = $0
}

END {
	if (calls){
		print last " " calls
		calls = ""
	}
}
